incident report 3 initial implementation
ECLK/pdf-service pull request #14
Opened 2020-02-26 16:06 UTC by nipuna777

Initial implementation of the template. Does not include data or all the district fields. 

I will attach a pdf downloaded from this request. Let me know what needs to be changed. 

[1582732648-iery.pdf](https://github.com/ECLK/pdf-service/files/4256783/1582732648-iery.pdf)

2020-02-27 09:52 UTC, MrClemRkz requested changes
This is awesome. now set variable for table body rows. try testing with, passing json data value to `/generate` endpoint. on the current directory of file will maintain a markdown file with example son value.

2020-02-27 15:38 UTC, nipuna777 commented
@MrClemRkz I've made the follwoing updates: 
1. Use JSON data for generating the report.
2. Save the JSON format in the markdown

The totals are not calculated, but they can be if needed. Let me know if any changes are required.

The new pdf is attached here: 
[1582817060-iwkqy.pdf](https://github.com/ECLK/pdf-service/files/4262403/1582817060-iwkqy.pdf)

2020-03-01 08:20 UTC, MrClemRkz approved these changes

2020-03-01 08:21 UTC, MrClemRkz approved these changes

2020-03-01 08:26 UTC, merged